# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/base.xdc

# Block Designs: bd/mani_readout/mani_readout.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mani_readout || ORIG_REF_NAME==mani_readout} -quiet] -quiet

# IP: bd/mani_readout/ip/mani_readout_processing_system7_0_0/mani_readout_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mani_readout_processing_system7_0_0 || ORIG_REF_NAME==mani_readout_processing_system7_0_0} -quiet] -quiet

# IP: bd/mani_readout/ip/mani_readout_LTC2324_read_0_0/mani_readout_LTC2324_read_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mani_readout_LTC2324_read_0_0 || ORIG_REF_NAME==mani_readout_LTC2324_read_0_0} -quiet] -quiet

# IP: bd/mani_readout/ip/mani_readout_axi_gpio_0_0/mani_readout_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mani_readout_axi_gpio_0_0 || ORIG_REF_NAME==mani_readout_axi_gpio_0_0} -quiet] -quiet

# IP: bd/mani_readout/ip/mani_readout_axi_gpio_0_1/mani_readout_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mani_readout_axi_gpio_0_1 || ORIG_REF_NAME==mani_readout_axi_gpio_0_1} -quiet] -quiet

# IP: bd/mani_readout/ip/mani_readout_axi_gpio_0_2/mani_readout_axi_gpio_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mani_readout_axi_gpio_0_2 || ORIG_REF_NAME==mani_readout_axi_gpio_0_2} -quiet] -quiet

# IP: bd/mani_readout/ip/mani_readout_rst_ps7_0_100M_0/mani_readout_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mani_readout_rst_ps7_0_100M_0 || ORIG_REF_NAME==mani_readout_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/mani_readout/ip/mani_readout_LTC2324_dummy_0_0/mani_readout_LTC2324_dummy_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mani_readout_LTC2324_dummy_0_0 || ORIG_REF_NAME==mani_readout_LTC2324_dummy_0_0} -quiet] -quiet

# IP: bd/mani_readout/ip/mani_readout_axi_gpio_0_3/mani_readout_axi_gpio_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mani_readout_axi_gpio_0_3 || ORIG_REF_NAME==mani_readout_axi_gpio_0_3} -quiet] -quiet

# IP: bd/mani_readout/ip/mani_readout_axi_gpio_0_4/mani_readout_axi_gpio_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mani_readout_axi_gpio_0_4 || ORIG_REF_NAME==mani_readout_axi_gpio_0_4} -quiet] -quiet

# IP: bd/mani_readout/ip/mani_readout_xbar_1/mani_readout_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mani_readout_xbar_1 || ORIG_REF_NAME==mani_readout_xbar_1} -quiet] -quiet

# IP: bd/mani_readout/ip/mani_readout_ps7_0_axi_periph_1/mani_readout_ps7_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mani_readout_ps7_0_axi_periph_1 || ORIG_REF_NAME==mani_readout_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/mani_readout/ip/mani_readout_auto_pc_0/mani_readout_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mani_readout_auto_pc_0 || ORIG_REF_NAME==mani_readout_auto_pc_0} -quiet] -quiet

# XDC: g:/My Drive/github/mani_readout/Xilinx/mani_readout_test/mani_readout_test.gen/sources_1/bd/mani_readout/mani_readout_ooc.xdc
