# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: g:/My Drive/github/mani_readout/Xilinx/mani_readout_test/mani_readout_test.srcs/sources_1/bd/mani_readout/ip/mani_readout_xbar_1/mani_readout_xbar_1.xci
# IP: The module: 'mani_readout_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/My Drive/github/mani_readout/Xilinx/mani_readout_test/mani_readout_test.gen/sources_1/bd/mani_readout/ip/mani_readout_xbar_1/mani_readout_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mani_readout_xbar_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: g:/My Drive/github/mani_readout/Xilinx/mani_readout_test/mani_readout_test.srcs/sources_1/bd/mani_readout/ip/mani_readout_xbar_1/mani_readout_xbar_1.xci
# IP: The module: 'mani_readout_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/My Drive/github/mani_readout/Xilinx/mani_readout_test/mani_readout_test.gen/sources_1/bd/mani_readout/ip/mani_readout_xbar_1/mani_readout_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mani_readout_xbar_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
