# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/prebys/Xilinx/mani_readout/mani_readout.srcs/sources_1/bd/mani_readout/ip/mani_readout_processing_system7_0_0/mani_readout_processing_system7_0_0.xci
# IP: The module: 'mani_readout_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/prebys/Xilinx/mani_readout/mani_readout.gen/sources_1/bd/mani_readout/ip/mani_readout_processing_system7_0_0/mani_readout_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mani_readout_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/prebys/Xilinx/mani_readout/mani_readout.srcs/sources_1/bd/mani_readout/ip/mani_readout_processing_system7_0_0/mani_readout_processing_system7_0_0.xci
# IP: The module: 'mani_readout_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/prebys/Xilinx/mani_readout/mani_readout.gen/sources_1/bd/mani_readout/ip/mani_readout_processing_system7_0_0/mani_readout_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mani_readout_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
